// trcwriter — запись буферов CAN в файлы PCAN .trc v1.1 (кнопка «↑CAN» экрана «GPIO ПУ»)
// версия: GPIO ПУ 2 (RPI-RES_260928_02), 2026-09-28
// формат: PEAK PCAN-Trace v1.1 - заголовок ;$FILEVERSION/;$STARTTIME (дни от 30.12.1899),
// строки «номер) смещение_мс Rx|Tx ID DLC данные», концы строк CRLF (смотрят на Windows)
#include "trcwriter.h"

#include <QDateTime>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QStorageInfo>
#include <QVector>
#include <QDebug>

#include <cstdio>
#include <unistd.h>
#include <sys/stat.h>

// запас свободного места, который оставляем системе
#define TRC_FREE_RESERVE (64LL * 1024 * 1024)
// оценка размера строки файла
#define TRC_LINE_SIZE 72

TrcWriter::TrcWriter(QList<Job> jobs_, QObject *parent) : QObject(parent)
{
    jobs = jobs_;

    mThread = new QThread();
    moveToThread(mThread);
    connect(mThread, &QThread::started, this, &TrcWriter::writeAll);
    connect(this, &QObject::destroyed, mThread, &QThread::quit);
    connect(mThread, &QThread::finished, mThread, &QObject::deleteLater);
    mThread->start(QThread::LowPriority);// сохранение не должно мешать приему
}

void TrcWriter::writeAll()
{
    bool ok = true;
    QString message;

    for (int i = 0; i < jobs.size(); i++)
    {
        quint64 frames = 0;
        QString error;
        QString name = QFileInfo(jobs[i].fileName).fileName();

        if (writeFile(jobs[i], frames, error))
            message += QString("%1%2 (%3)").arg(message.isEmpty() ? "" : ", ").arg(name).arg(frames);
        else
        {
            ok = false;
            message += QString("%1%2: ошибка - %3").arg(message.isEmpty() ? "" : ", ").arg(name, error);
        }
    }

    qDebug() << "GPIO PU: сохранение .trc:" << message;
    emit finished(ok, message);
    deleteLater();// тред остановится по destroyed()
}

QByteArray TrcWriter::header(qint64 startUs, const Job &job)
{
    QDateTime start = QDateTime::fromMSecsSinceEpoch(startUs / 1000);
    // $STARTTIME - дни от 30.12.1899 по местному времени
    qint64 localMs = start.toMSecsSinceEpoch() + qint64(start.offsetFromUtc()) * 1000;
    double oleDays = 25569.0 + double(localMs) / 86400000.0;

    QString rate = "unknown";
    if (job.bitrate)
        rate = (job.bitrate % 1000000 == 0) ? QString("%1 Mbit/s").arg(job.bitrate / 1000000)
                                           : QString("%1 kbit/s").arg(job.bitrate / 1000);

    QString h;
    h += ";$FILEVERSION=1.1\r\n";
    h += QString(";$STARTTIME=%1\r\n").arg(oleDays, 0, 'f', 10);
    h += ";\r\n";
    h += QString(";   %1\r\n").arg(job.fileName);
    h += ";\r\n";
    h += QString(";   Start time: %1.0\r\n").arg(start.toString("dd.MM.yyyy hh:mm:ss.zzz"));
    h += ";   Generated by Auto_Cleaner / GPIO PU\r\n";
    h += ";-------------------------------------------------------------------------------\r\n";
    h += ";   Connection                 Bit rate\r\n";
    h += QString(";   %1%2\r\n").arg(job.canName, -27).arg(rate);
    h += ";-------------------------------------------------------------------------------\r\n";
    h += ";   Message Number\r\n";
    h += ";   |         Time Offset (ms)\r\n";
    h += ";   |         |        Type\r\n";
    h += ";   |         |        |        ID (hex)\r\n";
    h += ";   |         |        |        |     Data Length Code\r\n";
    h += ";   |         |        |        |     |   Data Bytes (hex) ...\r\n";
    h += ";   |         |        |        |     |   |\r\n";
    h += ";---+--   ----+----  --+--  ----+---  +  -+ -- -- -- -- -- -- --\r\n";
    return h.toLatin1();
}

bool TrcWriter::writeFile(const Job &job, quint64 &frames, QString &error)
{
    quint64 first, end;
    job.buffer->range(first, end);

    QFileInfo info(job.fileName);
    QDir().mkpath(info.absolutePath());

    // хватит ли места
    QStorageInfo storage(info.absolutePath());
    qint64 need = qint64(end - first) * TRC_LINE_SIZE + 4096;
    if (storage.isValid() && storage.bytesAvailable() - need < TRC_FREE_RESERVE)
    {
        error = QString("мало места: нужно %1 МБ, свободно %2 МБ")
                .arg(need / 1048576 + 1).arg(storage.bytesAvailable() / 1048576);
        return false;
    }

    QFile file(job.fileName);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate))
    {
        error = file.errorString();
        return false;
    }

    // читаем буфер кусками, чтобы не держать его мьютекс долго
    QVector<CanTraceFrame> chunk(4096);
    QByteArray out;
    out.reserve(1 << 20);
    quint64 seq = first;
    qint64 startUs = 0;
    bool headerDone = false;
    char line[128];
    frames = 0;

    while (seq < end)
    {
        int n = job.buffer->copy(seq, int(qMin<quint64>(quint64(chunk.size()), end - seq)), chunk.data());
        if (n <= 0)
            break;

        if (!headerDone)
        {// смещения в файле считаем от первого кадра
            startUs = chunk[0].timeUs;
            out += header(startUs, job);
            headerDone = true;
        }

        for (int i = 0; i < n; i++)
        {
            const CanTraceFrame &f = chunk[i];
            char id[16];
            if (f.flags & CAN_TRACE_EXT)
                snprintf(id, sizeof(id), "%08X", f.id);
            else
                snprintf(id, sizeof(id), "%04X", f.id);

            // «     1)      1841.0  Rx     18FEF100  8  00 11 22 ...»
            int len = snprintf(line, sizeof(line), "%6llu)%12.1f  %s%13s  %u",
                               (unsigned long long)(++frames), double(f.timeUs - startUs) / 1000.0,
                               (f.flags & CAN_TRACE_TX) ? "Tx" : "Rx", id, (unsigned int)f.dlc);
            if (f.flags & CAN_TRACE_RTR)
                len += snprintf(line + len, sizeof(line) - len, "  RTR");
            else
            {
                for (int b = 0; b < f.dlc; b++)
                    len += snprintf(line + len, sizeof(line) - len, b ? " %02X" : "  %02X", f.data[b]);
            }
            out.append(line, len);
            out.append("\r\n", 2);
        }
        seq += quint64(n);

        // сбрасываем на диск по 1 МБ
        if (out.size() > (1 << 20) - 256)
        {
            if (file.write(out) != out.size())
            {
                error = file.errorString();
                return false;
            }
            out.clear();
        }
    }

    if (!headerDone)
        out += header(QDateTime::currentMSecsSinceEpoch() * 1000, job);// кадров не было - только заголовок
    if (!out.isEmpty() && file.write(out) != out.size())
    {
        error = file.errorString();
        return false;
    }
    file.flush();
    fsync(file.handle());
    file.close();

    // программа работает от root - отдаем каталог и файл владельцу каталога программы
    struct stat st;
    QString ownerDir = QFileInfo(info.absolutePath()).absolutePath();
    if (stat(QFile::encodeName(ownerDir).constData(), &st) == 0)
    {
        if (chown(QFile::encodeName(info.absolutePath()).constData(), st.st_uid, st.st_gid) != 0
                || chown(QFile::encodeName(job.fileName).constData(), st.st_uid, st.st_gid) != 0)
            qWarning() << "GPIO PU: chown" << job.fileName << "не удался";
    }
    return true;
}
